version: '3'
services:
  habits:
    container_name: habits
    build:
      context: ./service
      dockerfile: Dockerfile
    environment:
      - CONFIG_FILE=/app/config.ini
    volumes:
      - ./src/config.ini:/app/config.ini
    ports:
      - '80'
  dev:
    container_name: habits-dev
    build:
      context: ./service
      dockerfile: Dockerfile.dev
    volumes:
      - ./service/src:/app