version: '3'
services:
  backend:
    container_name: habits-backend
    image: habits:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - CONFIG_FILE=/app/config.ini
    volumes:
      - ./src/config.ini:/app/config.ini
    ports:
      - '80'