version: '3'
services:
  backend:
    container_name: habits-backend
    image: habits:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - CONFIG_FILE=/app/config.ini
    networks:
      - prod
    volumes:
      - ./src/config.ini:/app/config.ini
    ports:
      - '80'
  backend-test:
    container_name: habits-backend-test
    image: habits:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - CONFIG_FILE=/app/config.test.ini
    networks:
      - test
    volumes:
      - ./src/config.test.ini:/app/config.test.ini
    ports:
      - '80'
  tests:
    container_name: habits-tests
    image: test-runner:latest
    volumes:
      - ./tests:/tests
    env_file:
      - ./tests/envvars
    networks:
      - test
  test-runner:
    image: test-runner:latest
    build:
      context: ./test-runner/
      dockerfile: Dockerfile
  sql:
    container_name: habits-sql
    image: mariadb:10.5.8-focal
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d
    env_file:
      - ./sql/envvars
    networks:
      - prod
    ports:
      - '3306'
  sql-test:
    container_name: habits-sql-test
    image: mariadb:10.5.8-focal
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d
    env_file:
      - ./sql/envvarstest
    networks:
      - test
    ports:
      - '3306'
networks:
  test:
  prod: