version: '3'
services:
  habits:
    container_name: habits
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '80'
  dev:
    container_name: habits-dev
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./service/src:/app