version: '3'
services:
  habits:
    container_name: habits
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - CONFIG_FILE=/app/config.ini
    ports:
      - '80'
  dev:
    container_name: habits-dev
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./src:/app
  mocks:
    container_name: habits-mocks
    image: sheyenrath/wiremock.net:1.3.7
    command: --WireMockLogger WireMockConsoleLogger --ReadStaticMappings true
    volumes:
      - './mocks:/app/__admin/mappings'
    ports:
      - '80'